modimport("main/assets")
modimport("main/glassic_api_loader")

modimport("main/constants")
modimport("main/tuning")
modimport("main/strings")
modimport("main/characters")
modimport("main/rpc")
modimport("main/prefab_skins")
modimport("main/containers")
modimport("main/recipes")
modimport("main/actions")
modimport("main/postinit")
