local Hauntable = require("components/hauntable")

local _DoHaunt = Hauntable.DoHaunt
function Hauntable:DoHaunt(doer, ...)
    local _HAUNT_CHANCE_ALWAYS = TUNING.HAUNT_CHANCE_ALWAYS
    local _HAUNT_CHANCE_OFTEN = TUNING.HAUNT_CHANCE_OFTEN
    local _HAUNT_CHANCE_HALF = TUNING.HAUNT_CHANCE_HALF
    local _HAUNT_CHANCE_OCCASIONAL = TUNING.HAUNT_CHANCE_OCCASIONAL
    local _HAUNT_CHANCE_RARE = TUNING.HAUNT_CHANCE_RARE
    local _HAUNT_CHANCE_VERYRARE = TUNING.HAUNT_CHANCE_VERYRARE
    local _HAUNT_CHANCE_SUPERRARE = TUNING.HAUNT_CHANCE_SUPERRARE

    if doer and doer.prefab == "abigail" and (not doer:HasTag("shadow_abigail") or doer:HasTag("gestalt")) then
        TUNING.HAUNT_CHANCE_ALWAYS = 1
        TUNING.HAUNT_CHANCE_OFTEN = 1
        TUNING.HAUNT_CHANCE_HALF = 1
        TUNING.HAUNT_CHANCE_OCCASIONAL = 1
        TUNING.HAUNT_CHANCE_RARE = 0.25
        TUNING.HAUNT_CHANCE_VERYRARE = .005
        TUNING.HAUNT_CHANCE_SUPERRARE = 0.1
    end

    _DoHaunt(self, doer, ...)

    TUNING.HAUNT_CHANCE_ALWAYS = _HAUNT_CHANCE_ALWAYS
    TUNING.HAUNT_CHANCE_OFTEN = _HAUNT_CHANCE_OFTEN
    TUNING.HAUNT_CHANCE_HALF = _HAUNT_CHANCE_HALF
    TUNING.HAUNT_CHANCE_OCCASIONAL = _HAUNT_CHANCE_OCCASIONAL
    TUNING.HAUNT_CHANCE_RARE = _HAUNT_CHANCE_RARE
    TUNING.HAUNT_CHANCE_VERYRARE = _HAUNT_CHANCE_VERYRARE
    TUNING.HAUNT_CHANCE_SUPERRARE = _HAUNT_CHANCE_SUPERRARE
end
